package dev.processsearch.index;

import java.util.List;

import dev.processsearch.ProcessSearch;
import dev.processsearch.ProcessSearchConfig;
import mezz.jei.api.recipe.IRecipeManager;
import mezz.jei.api.recipe.RecipeType;
import mezz.jei.api.recipe.category.IRecipeCategory;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.crafting.RecipeHolder;

/**
 * A cheap answer to "are these the same recipes I already indexed?".
 *
 * <p>JEI rebuilds its runtime on every world join, but in the common case -- leaving a singleplayer
 * world and joining a server running the same pack -- the recipe data is identical and rebuilding
 * the index is pure waste. If the fingerprint matches, the previous index still describes the world
 * that was just joined.
 *
 * <p>Taking it costs one pass over the recipe lists and nothing else. That is the whole point: the
 * expensive half of a build is the adapter chain and JEI's layout builder, neither of which this
 * touches, so the check is worth taking even when it fails.
 *
 * <p>Every sum is order-independent, because reload order is not guaranteed stable and a reordering
 * is not a change. Sums rather than XOR, since XOR would cancel a pair of identical entries instead
 * of counting them.
 *
 * <p>Recipes that are not datapack recipes have no stable id -- they are generated by their
 * category, and their identity hash changes every reload. Those contribute their count only, which
 * catches a category gaining or losing entries but not one silently rewriting them. That is the
 * honest limit of what can be checked without doing the build.
 */
public record Fingerprint(int categories, long recipes, long idHash, int generation) {

    public static Fingerprint of(IRecipeManager manager, List<IRecipeCategory<?>> categories) {
        if (manager == null || categories == null) {
            return null;
        }
        long recipes = 0;
        long idHash = 0;
        int counted = 0;
        for (IRecipeCategory<?> category : categories) {
            RecipeType<?> type = category.getRecipeType();
            long forCategory = hashOf(type.getUid());
            try {
                for (Object recipe : lookup(manager, type)) {
                    recipes++;
                    if (recipe instanceof RecipeHolder<?> holder) {
                        forCategory += hashOf(holder.id());
                    }
                }
            } catch (RuntimeException | LinkageError e) {
                // A category that cannot be listed contributes its id and nothing else, which is
                // stable across reloads and so does not make the check spuriously fail.
                ProcessSearch.LOGGER.debug("Fingerprint skipped {}: {}", type.getUid(), e.toString());
            }
            idHash += forCategory;
            counted++;
        }
        return new Fingerprint(counted, recipes, idHash, ProcessSearchConfig.generation());
    }

    @SuppressWarnings("unchecked")
    private static Iterable<?> lookup(IRecipeManager manager, RecipeType<?> type) {
        RecipeType<Object> erased = (RecipeType<Object>) type;
        return manager.createRecipeLookup(erased).includeHidden().get()::iterator;
    }

    private static long hashOf(ResourceLocation id) {
        return id == null ? 0L : id.toString().hashCode() & 0xFFFFFFFFL;
    }
}
